### PR TITLE
[UPD] setWallpaper command to allow multiple screens

### PR DESCRIPTION
**Pull request by akramsaouri**
✅ Worked on MacOS Majove V10.14.5 (with dual screen)

### CODE REVIEW

**Comment by akramsaouri** [comment]
#1

**Comment by evertdespiegeleer** [comment]
This indeed seems to work great. Thank you for your contribution!

**Comment by akramsaouri** [comment]
No **thank you** for making this app, hit me up if there is a feature I can help with 🙏

**Comment by borsboom** [comment]
Has this change been released?  I just downloaded the app from https://prettyearth.evertdespiegeleer.com/ and it doesn't seem to have this yet.  I was able to edit the `setWallpaper.js` file inside the .app bundle though and after making the change I can confirm it's working for me as well.

**Comment by evertdespiegeleer** [comment]
> Has this change been released? I just downloaded the app from https://prettyearth.evertdespiegeleer.com/ and it doesn't seem to have this yet. I was able to edit the `setWallpaper.js` file inside the .app bundle though and after making the change I can confirm it's working for me as well.

It hasn't. I merged the commit, but I was planning on adding more features. I however don't really have the time to do so, so I'll be releasing this change soon.

**Pull request merged**
